<?php

namespace Tests\Unit\Service;

use App\Location;
use App\Services\LocationService;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\TestCase;

class LocationServiceTest extends TestCase
{
    use DatabaseMigrations;
    use DatabaseTransactions;

    protected LocationService $service;
    protected array $create;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->service = app(LocationService::class);
        $this->create = [
            'short' => 'SHORT',
            'long'  => 'LONG',
        ];
    }

    public function test_first_or_create_finds_from_database(): void
    {
        $location = factory(Location::class)->create($this->create + ['id' => 1]);

        $result = $this->service->firstOrCreate($location->id, $this->create);

        $this->assertEquals($location->id, $result->id);
    }

    public function test_first_or_create_creates_if_missing(): void
    {
        $location = factory(Location::class)->create($this->create + ['id' => 1]);

        $this->service->firstOrCreate($location->id, $this->create);

        $this->assertDatabaseHas('locations', $this->create);
    }
}
