<?php

return [
    'view_all'        => 'View all transactions',
    'no_transactions' => 'There are no transactions!',
    'description'     => 'Last :count transactions generated by this server',
];
